inherit: null
exp_name: contact_model
# data and loading
base_dir: data/arctic_processed_data
end_frame: null
base_frame: 100
batch_size: 100
input_dim: 378
num_workers: 8
normalize_data: true
pred_horizon: 64
num_features: 3
num_bps_points: 512
global_state_dim: 7
stat_dict_path: assets/contact_norm_stats.pkl
# architecture
ff_size: 1024
activation: gelu
dropout: 0.1
latent_cond_dim: 512
mlp_layer1_dim: 1024
mlp_layer2_dim: 1024
num_heads: 4
num_layers: 8
obj_latent_dim: 1024
# training
load_pretrained: false
lr: 1.0e-05
start_epochs: 0
num_epochs: 200
num_timesteps: 50
pretrained_model_path: null
# output
save_root_dir: experiments/
save_checkpt_epoch: 100
use_wandb: false
wandb_entity: enter_your_credential
wandb_pj_name: bimart_contact_model
